OAuth2\ServerBundle\Entity\Scope:
    type: entity
    table: oauth_scope
    id:
        id:
            type:       integer
            generator:
              strategy: AUTO
    fields:
        scope:
            type:       string
            length:     255
            unique:     true
        description:
            type:       string
            length:     255
    lifecycleCallbacks: {  }
