OAuth2\ServerBundle\Entity\User:
    type: entity
    table: oauth_user
    id:
        id:
            type:       integer
            generator:
              strategy: AUTO
    fields:
        username:
            type:       string
            length:     255
            unique:     true
        firstname:
            type:       string
            length:     255
            nullable:   true
        lastname:
            type:       string
            length:     255
            nullable:   true
        middlename:
            type:       string
            length:     255
            nullable:   true
        password:
            type:       string
            length:     255
        salt:
            type:       string
            length:     255
        roles:
            type:       simple_array
            nullable:   true
        scopes:
            type:       simple_array
            nullable:   true
        birthdate:
            type:       date
            nullable:   true
        email:
            type:       string
            lenght:     100
            nullable:   true
            unique:     true
    lifecycleCallbacks: {  }
