OAuth2\ServerBundle\Entity\User:
    type: entity
    table: oauth_user
    id:
        id:
            type:       integer
            generator:
              strategy: AUTO
    fields:
        firstname:
            type:       string
            length:     255
            nullable:   true
        lastname:
            type:       string
            length:     255
            nullable:   true
        middlename:
            type:       string
            length:     255
            nullable:   true
        birthdate:
            type:       date
            nullable:   true
        scopes:
            type:       simple_array
            nullable:   true
    lifecycleCallbacks: {  }
